#
# -------------------------------------------
# SIPA BOOT CONFIGURATION
# -------------------------------------------
#
sipa.boot:
  #
  # -------------------------------------------
  # DYNAMIC DATA SOURCE CONFIGURATION
  # -------------------------------------------
  #
  datasource:
    enabled: true
    names:
      - mysql
    dynamics:
      mysql:
        datasource:
          names: master,slave0
          master:
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://xx:3306/water_gas_service?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=false&serverTimezone=PST&allowPublicKeyRetrieval=true
            username: root
            password: xx
          slave0:
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://xx:3306/water_gas_service?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=false&serverTimezone=PST&allowPublicKeyRetrieval=true
            username: root
            password: xx
        masterslave:
          load-balance-algorithm-type: round_robin
          name: ms
          master-data-source-name: master
          slave-data-source-names: slave0
